config/routes.rb
Status::Application.routes.draw do
  resources :infos
  resources :accounts
  resources :sessions
  resources :statusupdates do
    resources :comments
  end

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "accounts#new", :as => "signup"
  get "timeline" => "statusupdates#index", :as => "timeline"

  match '/logout', :to => 'sessions#destroy'

  root :to => 'sessions#new'

end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Paranoia
  

  attr_accessible :body, :commenter

  field :commenter, :type => String
  field :body, :type => String
  field :deleted_at, :type => Time
  
  #acts_as_paranoid

  validates :commenter, :body, :presence => true
  validates :commenter, :length => { :minimum => 2 }
  validates :commenter, :length => { :maximum => 20 }

  embedded_in :statusupdate, :inverse_of => :comments
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new    
    @comment = Comment.new
  end

  def create
    @account = Account.find_by(_id: session[:account_id])
    @statusupdate = Statusupdate.find_by(_id: params[:statusupdate_id])
    @comment = @statusupdate.comments.new(params[:comment])
    @comment.commenter = @account.username
    if @comment.save
      redirect_to statusupdate_path(@statusupdate), :notice => "Comment berhasil!"
    else
      redirect_to statusupdate_path(@statusupdate), :notice => "Comment Gagal!"
    end    
  end

  def index
    @account = Account.find(session[:account_id])
    @statusupdate = Statusupdate.find(params[:statusupdate_id])
    @comments = @statusupdate.comments.order_by([:created_at, :asc]).page(params[:page]).per(3)
  end

  def show
    @account = Account.find_by(_id: session[:account_id])
    @statusupdate = Statusupdate.find_by(_id: params[:statusupdate_id])
    @comment = @statusupdate.comments.unscoped.find_by(_id: params[:id])
    authorize! :read, @comment #if @account && @account.role != 'admin' && @comment && @comment.deleted_at != nil 

  end

  def edit
    @account = Account.find(session[:account_id])
    @statusupdate = Statusupdate.find_by(_id: params[:statusupdate_id])
    @comment = @statusupdate.comments.find_by(_id: params[:id])
    authorize! :read, @account unless @comment && @comment.commenter == @account.username
  end

  def update
    @statusupdate = Statusupdate.find(params[:statusupdate_id])
    @comment = @statusupdate.comments.find(params[:id])
    if @comment.update_attributes(params[:comment])
      redirect_to statusupdate_path(@statusupdate), :notice => "Comment Successfull edited"
    else
      render "edit", :notice => "Error edited status"
    end
  end


  def destroy
  	@statusupdate = Statusupdate.find(params[:statusupdate_id])
  	@comment = @statusupdate.comments.find(params[:id])
  	@comment.destroy
  	redirect_to statusupdate_path(@statusupdate)
  	
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% for comment in @comments %>
	<table class="table table-striped">
		<tr>
			<td><b><%= comment.commenter %></b>  <%= comment.body %></td>
			<% if !comment.deleted_at.nil? %>
				<td width="3%">
					<i>deleted</i>
				</td>		
			<% end %>
			<td width="3%">
				<%= link_to 'Show', statusupdate_comment_path(@statusupdate, comment), :class => 'btn btn-mini btn-mini' %>
			</td>		
			<td width="3%">
				<% if can? :update, comment %>
					<% if comment.deleted_at == nil %>
						<%= link_to 'Edit', edit_statusupdate_comment_path(@statusupdate, comment), :class => 'btn btn-mini btn-mini' %>
					<% end %>
				<% end %>
			</td>
			<td width="3%">
				<% if can? :destroy, comment %>
					<% if comment.deleted_at == nil %>
						<%= link_to 'Delete' , [@statusupdate, comment], :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-mini btn-danger' %>
					<% end %>
				<% end %>
			</td>
		</tr>	
	</table>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@statusupdate, @statusupdate.comments.build]) do |c| %>	
	<table>		
		<tr>
			<td><%= c.text_area :body, :size => "80x1"%></td>
		</tr>
		<tr>
			<td><%= c.submit "Add Comment", :class => 'btn btn-primary'%></td>
		</tr>
	</table>  
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= form_for [@statusupdate, @comment] do |f| %>
	<%= f.text_area :body, :size => "100x2" %> <br>
	<%= f.submit "Edit Comment", :class => 'btn btn-primary' %>
<% end %>
<%= link_to "Back to status",  statusupdate_path(@statusupdate), :class => 'btn btn-mini' %>

app/views/comments/index.html.erb
<h2>Listing Comment from status </h2>
<b><%= @statusupdate.content %></b><br>
by <%= @statusupdate.username %>
<br><br>
<%= paginate @comments %>
	<%= render "comments/comment" %>
<%= paginate @comments %>
<br>
<%= link_to "Back to status",  statusupdate_path(@statusupdate), :class => 'btn btn-mini' %>

app/views/comments/show.html.erb
<h1>Show Comment</h1>
<b>comment by <%= @comment.commenter %> : </b>
<p>
	<%= @comment.body %>
</p>
<%= link_to "Back to status",  statusupdate_path(@statusupdate), :class => 'btn btn-mini' %>
<% if can? :update, @comment %>
	<% if @comment.deleted_at == nil %>
		<%= link_to 'Edit', edit_statusupdate_comment_path(@statusupdate, @comment), :class => 'btn btn-mini btn-mini' %>
	<% end %>
<% end %>