config/routes.rb
Status::Application.routes.draw do
  resources :infos
  resources :accounts
  resources :sessions
  resources :statusupdates do
    resources :comments
  end

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "accounts#new", :as => "signup"
  get "timeline" => "statusupdates#index", :as => "timeline"

  match '/logout', :to => 'sessions#destroy'

  root :to => 'sessions#new'

end

app/models/statusupdate.rb
class Statusupdate

  include Mongoid::Document
  include Mongoid::Paranoia

  attr_accessible :content, :updatetime, :username

  field :username, :type => String
  field :content, :type => String
  field :deleted_at, :type => Time
  field :updatetime, :type => DateTime

  #acts_as_paranoid

  validates :username, :content, :presence => true
  validates :username, :length => { :minimum => 2 }
  validates :username, :length => { :maximum => 20 }

  def self.ignore_paranoia
    all.tap {|criteria| criteria.selector.delete(:deleted_at)}
  end

  embeds_many :comments
end

app/controllers/statusupdates_controller.rb
class StatusupdatesController < ApplicationController

	def index
		authorize! :read, @account		
		if session[:account_id] != nil
			@account = Account.find_by(_id: session[:account_id])
			if @account.role == "admin"
				@statusupdates = Statusupdate.unscoped.order_by([:updatetime, :desc]).page(params[:page]).per(5)
			else
				@statusupdates = Statusupdate.order_by([:updatetime, :desc]).page(params[:page]).per(3)
			end
			@statusupdate = Statusupdate.new									
		else
			redirect_to new_session_path
		end
	end

	def show	    
		@account = Account.find_by(_id: session[:account_id])
		@statusupdate = Statusupdate.unscoped.find_by(_id: params[:id])
		authorize! :read, @statusupdate# if @account && @account.role != 'admin' && @statusupdate && @statusupdate.deleted_at != nil 
		@comments = @statusupdate.comments.page(params[:page]).per(3)
		if @account.role == "admin"
			@comments = @statusupdate.comments.unscoped.page(params[:page]).per(3)
		else
			@comments = @statusupdate.comments.page(params[:page]).per(3)
		end
	end

	def new
		@statusupdate = Statusupdate.new
	end

	def create
		@account = Account.find_by(_id: session[:account_id])
		@statusupdate = Statusupdate.new(params[:statusupdate])		
		@statusupdate.username = @account.username
		@statusupdate.updatetime = Time.now
		if @statusupdate.save
			redirect_to statusupdates_path, :notice => "Your Status has been updated"
		else
			render "new"
		end
	end

	def edit
		@account = Account.find_by(_id: session[:account_id])
		@statusupdate = Statusupdate.find_by(_id: params[:id])
		authorize! :read, @account unless @account.username == @statusupdate.username
	end

	def update
		@account = Account.find(session[:account_id])
		@statusupdate = Statusupdate.find(params[:id])
		if @statusupdate.update_attributes(params[:statusupdate])
			redirect_to statusupdates_path, :notice => "Your Status has been edited"
		else
			render "edit", :notice => "Error edited status"
		end
	end

	def destroy
		@statusupdate = Statusupdate.find(params[:id])
		@statusupdate.destroy
		redirect_to statusupdates_path, :notice => "Your Status has been deleted"
	end
	
	def recovery
		
	end

end

app/helpers/statusupdates_helper.rb
module StatusupdatesHelper
end

app/views/statusupdates/_form.html.erb
<%= form_for @statusupdate do |su| %>
	<% if @statusupdate.errors.any? %>
		<b>Errors : </b><br>
		<ul>
			<% @statusupdate.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>	
		</ul>
	<% end %>
	<table class="table table-striped">
		<tr>
			<td rowspan=3>
				<div class="center">
				<%= image_tag @current_user.image_url(:thumb) if @current_user.image? %>
				</div>
			</td>			
		</tr>
			<td><%= su.text_area :content,:size => "150x2", :placeholder => "What's on your mind now?" %></td>
		</tr>
		<tr>
			<td><%= su.submit "Update Status", :class => 'btn btn-primary' %></td>			
		</tr>
	</table>
<% end %>
<hr>

app/views/statusupdates/_statusupdate.html.erb
<%= paginate @statusupdates %>
<%# @statusupdates.sort_by{|e| -e[:id]}.each do |statusupdate| %>
<% for statusupdate in @statusupdates %>
	<table>
		<tr>
			<td>
				<div class="center">
					<div class="hidden">
						<%= @ava = Account.find_by(username: statusupdate.username) %>
					</div>					
					<%= image_tag @ava.image_url(:thumb) if @ava.try(:image?) %>
				</div>
			</td>
			<td>
				&nbsp;&nbsp;&nbsp;
			</td>
			<td>
				<b><%= statusupdate.username %></b> <br>
				<%= statusupdate.content %> <br>
				<small>
					<i><%= link_to statusupdate.comments.all.count.to_s << " comments",  statusupdate_path(statusupdate) %></i> <br>
					<%= statusupdate.updatetime %> <br>
						<% if can? :update, statusupdate %>
							<% if statusupdate.deleted_at == nil %>
								<%= link_to "Edit", edit_statusupdate_path(statusupdate), :class => 'btn btn-mini'%>
							<% end %>
						<% end %>
						<% if can? :destroy, statusupdate %>
							<% if statusupdate.deleted_at == nil %>
								<%= link_to "Delete", statusupdate, :confirm => "Are you sure?", :method => :delete , :class => 'btn btn-mini btn-danger' %>
							<% end %>
						<% end %>						
						<% if !statusupdate.deleted_at.nil? %>
							<i>deleted</i>
						<% end %>					
				</small>
			</td>
		</tr>
	</table>
	<hr>
<% end %>

<%= paginate @statusupdates %>

app/views/statusupdates/edit.html.erb
<%= form_for @statusupdate do |su| %>
	<b>Your status at </b> <small><%= @statusupdate.updatetime %></small><br>	
	<table>		
		<tr>
			<td><%= su.text_area :content, :size => "40x2" %></td>
		</tr>
		<tr>
			<td><%= su.submit "Edit Status", :class => 'btn btn-primary' %></td>
		</tr>
	</table>
<% end %>

app/views/statusupdates/index.html.erb
<%= render "statusupdates/form" %>
<%= render "statusupdates/statusupdate" %>

app/views/statusupdates/new.html.erb
<h1>What's on your mind now?</h1>
<%= render "statusupdates/form" %>

app/views/statusupdates/show.html.erb
<b><%= @statusupdate.username %></b> <br>
<p>
	<%= @statusupdate.content %> <br>
	<small><small><%= @statusupdate.updatetime %></small></small>
</p>
<b>Comments</b><br>
<%= paginate @comments %><br>
<%= render "comments/comment" %>
<%= paginate @comments %>
<b>Add a comment:</b>
<%= render "comments/form" %>

<% if can? :update, @statusupdate %>
	<% if @statusupdate.deleted_at == nil %>
		<%= link_to 'Edit Status', edit_statusupdate_path(@statusupdate), :class => 'btn btn-mini'%>
	<% end %>
<% end %>	

<%= link_to 'Back to Status Updates', statusupdates_path, :class => 'btn btn-mini'%> 
<% if @statusupdate.deleted_at == nil %>
	<%= link_to 'View All Comments', statusupdate_comments_path(@statusupdate), :class => 'btn btn-mini'%> 
<% end %>