config/routes.rb
Status::Application.routes.draw do
  resources :infos
  resources :accounts
  resources :sessions
  resources :statusupdates do
    resources :comments
  end

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "accounts#new", :as => "signup"
  get "timeline" => "statusupdates#index", :as => "timeline"

  match '/logout', :to => 'sessions#destroy'

  root :to => 'sessions#new'

end

app/models/info.rb
class Info < ActiveRecord::Base
  attr_accessible :name, :detailinfos_attributes
  has_many :detailinfos, :dependent => :destroy
  accepts_nested_attributes_for :detailinfos, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  # GET /infos
  # GET /infos.json
  def index
    if session[:account_id] != nil
      @account = Account.find(session[:account_id]) if session[:account_id]     

      @infos = Info.all

	    respond_to do |format|
	      format.html # index.html.erb
	      format.json { render json: @infos }
	    end 
    else
      redirect_to new_session_path
    end
    
  end

  # GET /infos/1
  # GET /infos/1.json
  def show
  	if session[:account_id] != nil
			@account = Account.find(session[:account_id]) if session[:account_id]     
		else
      redirect_to new_session_path
    end
    @info = Info.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @info }
    end
  end

  # GET /infos/new
  # GET /infos/new.json
  def new
  	if session[:account_id] != nil
			@account = Account.find(session[:account_id]) if session[:account_id]     
			@info = Info.new
			3.times { @info.detailinfos.build }
			
	    respond_to do |format|
	      format.html # new.html.erb
	      format.json { render json: @info }
	    end
		else
      redirect_to new_session_path
    end    
  end

  # GET /infos/1/edit
  def edit
  	if session[:account_id] != nil
			@account = Account.find(session[:account_id]) if session[:account_id]
	    @info = Info.find(params[:id])
	  else
      redirect_to new_session_path
    end
  end

  # POST /infos
  # POST /infos.json
  def create
    @info = Info.new(params[:info])

    respond_to do |format|
      if @info.save
        format.html { redirect_to @info, notice: 'Info was successfully created.' }
        format.json { render json: @info, status: :created, location: @info }
      else
        format.html { render action: "new" }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /infos/1
  # PUT /infos/1.json
  def update
    @info = Info.find(params[:id])

    respond_to do |format|
      if @info.update_attributes(params[:info])
        format.html { redirect_to @info, notice: 'Info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infos/1
  # DELETE /infos/1.json
  def destroy
    @info = Info.find(params[:id])
    @info.destroy

    respond_to do |format|
      format.html { redirect_to infos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/views/infos/_detailinfo_fields.html.erb
<fieldset>
	<%= f.label :content, "Detail Information" %>
	<%= f.text_area :content, :rows => 2 %> <br>
	<%= f.hidden_field :_destroy %>
	<%= link_to "remove", "#{}", class: "remove_fields" %>
</fieldset>

app/views/infos/_form.html.erb
<%#= simple_form_for(@info) do |f| %>
  <%#= f.error_notification %>
<%= form_for @info do |f| %>  
  <%= f.error_messages %>

  <div class="form-inputs">
  	<%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <%= f.fields_for :detailinfos do |builder| %>
  	<%= render 'detailinfo_fields', f: builder %>
  <% end %>
  
  <br>
  <%= link_to_add_fields 'Add Detail Information', f, :detailinfos %><br><br>


  <%= f.submit "Information", :class => 'btn btn-primary'%>
<% end %>

app/views/infos/edit.html.erb
<h1>Editing info</h1>

<%= render 'form' %>

<%= link_to 'Show', @info, :class => 'btn btn-mini' %>
<%= link_to 'Back', infos_path, :class => 'btn btn-mini' %>

app/views/infos/index.html.erb
<h2>Listing <%= @account.username %> Information </h2>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @infos.each do |info| %>
  <tr>
    <td><%= info.name %></td>
    <td width="3%"><%= link_to 'Show', info, :class => 'btn btn-mini' %></td>
    <td width="3%"><%= link_to 'Edit', edit_info_path(info), :class => 'btn btn-mini' %></td>
    <td width="3%"><%= link_to 'Destroy', info, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Information', new_info_path, :class => 'btn btn-primary'%>

app/views/infos/new.html.erb
<h1>New info</h1>

<%= render 'form' %>

<%= link_to 'Back', infos_path, :class => 'btn btn-mini'%>

app/views/infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @info.name %>
</p>

<ol>
	<% for detailinfo in @info.detailinfos %>
		<li><%=h detailinfo.content %></li>
	<% end %>
</ol>


<%= link_to 'Edit', edit_info_path(@info), :class => 'btn btn-mini' %>
<%= link_to 'Back', infos_path, :class => 'btn btn-mini' %>