config/routes.rb
Status::Application.routes.draw do
  resources :infos
  resources :accounts
  resources :sessions
  resources :statusupdates do
    resources :comments
  end

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "accounts#new", :as => "signup"
  get "timeline" => "statusupdates#index", :as => "timeline"

  match '/logout', :to => 'sessions#destroy'

  root :to => 'sessions#new'

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Status</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>        
        <a class="brand" href="#">Update your status!</a>
        <div class="nav-collapse">
          <ul class="nav">
            <% if session[:account_id] != nil %>
              <li>
                <%= link_to @account.username.to_s << " Timeline", statusupdates_path %>
              </li>
              <li>
                <%= link_to('Edit Account', edit_account_path(@account)) %>
              </li>
            <% else %>
              <li>
                <%= link_to('Sign up', new_account_path)  %>
              </li>
            <% end %>
            <% if session[:account_id] != nil %>
              <li>
                <%= link_to('Logout', logout_path, :method=>'delete') %>
              </li>
            <% else %>
              <li>
                <%= link_to('Login', new_session_path)  %>
              </li>
            <% end %>  
          </ul>
        </div>
      </div>
    </div>
  </div>
	
<div id="main" role="main">
  <div class="container">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
        <a class="close" data-dismiss="alert">x</a>
        <%= msg %>
      </div>
    <% end %>
    <div class="row">
      <div class="span9">
        <%= yield %>
      </div>
      <div class="span3">
        <h2>About Us</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>        
      </div>
    </div>
  </div>
</div>

</body>
</html>